### ISSUE TITLE
Difficulte a lancer le projet

### ISSUE THREAD

**Issue by BrightkyEfoo** [tamaroas/wenlo#2]
# Installation des dependances
### 1- NPM install
Bon la premiere fois tout passait creme, on avait cree le projet ensemble et tout ce  passait bien
Je suis revenu et au moment de lancer le projet j'avais des difficultes avec npm install.
les dependances s'isntallaient avec beaucoup de **vulnerabilites**
### 2- Suppression du package-lock.json
Meme apres avoir supprime le package-lock.json et tout le node_module, je ne m'ensortais toujours pas

`Faut vraiment pas que ca se reproduise, Et pour ca il nous faut trouver la source`

**Comment by tamaroas** [comment]
Oui mais je ne sais pas parce que je n'avait remarqué aucun problème du genre dev mon coté .
